// src/app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./Footer"; // Import from the same directory

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Storage Planner",
  description: "Generated by buildthehomelab.com",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
