name: Build and Push ARM Docker images

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/arm64, linux/arm/v7]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: 'arm64,arm'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Create .babelrc
        run: |
          echo '{"presets": ["next/babel"]}' > .babelrc

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          platforms: ${{ matrix.platform }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/storage-planner:latest-${{ matrix.platform == 'linux/arm64' && 'arm64' || 'armv7' }}
          build-args: |
            TARGETARCH=${{ matrix.platform == 'linux/arm64' && 'arm64' || 'arm' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
