name: Create Multi-Architecture Manifest

on:
  workflow_run:
    workflows: ["Build and Push AMD64 Docker image", "Build and Push ARM Docker images"]
    types:
      - completed
    branches: [main, master]
  workflow_dispatch:  # Allows manual triggering

jobs:
  create-manifest:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
          
      - name: Create manifest
        run: |
          docker manifest create ghcr.io/${{ github.repository_owner }}/storage-planner:latest \
            ghcr.io/${{ github.repository_owner }}/storage-planner:latest-amd64 \
            ghcr.io/${{ github.repository_owner }}/storage-planner:latest-arm64 \
            ghcr.io/${{ github.repository_owner }}/storage-planner:latest-armv7
            
          docker manifest create ghcr.io/${{ github.repository_owner }}/storage-planner:${{ github.sha }} \
            ghcr.io/${{ github.repository_owner }}/storage-planner:${{ github.sha }}-amd64 \
            ghcr.io/${{ github.repository_owner }}/storage-planner:latest-arm64 \
            ghcr.io/${{ github.repository_owner }}/storage-planner:latest-armv7
            
      - name: Push manifest
        run: |
          docker manifest push ghcr.io/${{ github.repository_owner }}/storage-planner:latest
          docker manifest push ghcr.io/${{ github.repository_owner }}/storage-planner:${{ github.sha }}
